### ISSUE TITLE
ERROR You must supply options.input to rollup

### ISSUE THREAD

**Issue by asterikx** [vbenjs/vite-plugin-html#31]
Using `vite-plugin-html@3.0.5` with `vite@2.8.0` leads to the following error: `ERROR  You must supply options.input to rollup`.

Removing the plugin from the plugin section fixes the error and makes vite build successfully.

```
vite v2.8.0 building for production...                                   12:13:03
✓ 0 modules transformed.                                                 12:13:03

 ERROR  You must supply options.input to rollup                          12:13:03


 ERROR  error during build:                                              12:13:03
Error: You must supply options.input to rollup
    at Graph.generateModuleGraph (/Users/erikmuller/detelling/.yarn/cache/rollup-npm-2.67.1-27edb63f67-4320927ae9.zip/node_modules/rollup/dist/shared/rollup.js:22982:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Graph.build (/Users/erikmuller/detelling/.yarn/cache/rollup-npm-2.67.1-27edb63f67-4320927ae9.zip/node_modules/rollup/dist/shared/rollup.js:22925:9)
    at async rollupInternal (/Users/erikmuller/detelling/.yarn/cache/rollup-npm-2.67.1-27edb63f67-4320927ae9.zip/node_modules/rollup/dist/shared/rollup.js:23547:9)
    at async doBuild (/Users/erikmuller/detelling/.yarn/__virtual__/vite-virtual-b4106f023d/0/cache/vite-npm-2.8.0-75c8dda402-b6deeab38f.zip/node_modules/vite/dist/node/chunks/dep-c9c9d3e5.js:39094:24)
    at async build (/Users/erikmuller/detelling/.yarn/__virtual__/vite-virtual-b4106f023d/0/cache/vite-npm-2.8.0-75c8dda402-b6deeab38f.zip/node_modules/vite/dist/node/chunks/dep-c9c9d3e5.js:38930:16)
    at async CAC.<anonymous> (/Users/erikmuller/detelling/.yarn/__virtual__/vite-virtual-b4106f023d/0/cache/vite-npm-2.8.0-75c8dda402-b6deeab38f.zip/node_modules/vite/dist/node/cli.js:738:9)
```

```ts
// vite.config.ts

export default defineConfig({
  cacheDir: '.vite',
  plugins: [
    react(),
    createHtmlPlugin(),
  ],
  optimizeDeps: {
    include: ['react/jsx-runtime'],
  },
  resolve: {
    alias: {
      '@/': '/src/',
    },
  },
});
```

**Comment by christianlmc** [comment]
Not sure if this would count as workaround or a solution, but this worked for me:

```js
export default defineConfig({
       // ...
        build: {
            rollupOptions: {
                input: '/path/to/your/index.html',
            },
        },
});
```

**Comment by bluwy** [comment]
Tangentially related, but thought I'd point out:

https://github.com/vbenjs/vite-plugin-html/blob/689324bda0594be4175450da8e2ab0dd1c8755eb/packages/core/src/htmlPlugin.ts#L34

The `mergeConfig` can be omitted and directly return the object. Vite runs another `mergeConfig` internally too.

**Comment by anncwb** [comment]
try v3.0.6

**Comment by asterikx** [comment]
@anncwb I can confirm that the error no longer occurs in v3.0.6. Thanks for the quick fix!
