### ISSUE TITLE
Build failed using nodejs v12.22.1

### ISSUE THREAD

**Issue by Hope410** [vbenjs/vite-plugin-html#36]
Hello, after updating the package to v3.0.6, i've realised that vite build using node v12.22.1 failed with this error message:
```
/home/gitlab-runner/builds/f-zTB-5a/0/ispp/arm-school-front-end/node_modules/vite-plugin-html/dist/index.cjs:139
          html = await server.transformIndexHtml?.(url, html, req.originalUrl);
                                                 ^
SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:[86](https://gitlab.iteco.mobi/ispp/arm-school-front-end/-/jobs/99103#L86)3:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:8[87](https://gitlab.iteco.mobi/ispp/arm-school-front-end/-/jobs/99103#L87):19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/gitlab-runner/builds/f-zTB-5a/0/ispp/arm-school-front-end/vite.config.ts:38:20)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.require.extensions.<computed> [as .ts] (/home/gitlab-runner/builds/f-zTB-5a/0/ispp/arm-school-front-end/node_modules/vite/dist/node/chunks/dep-c9c9d3e5.js:71344:20)
```

**Comment by lisonge** [comment]
<https://node.green/#ES2020-features-optional-chaining-operator----->

**Comment by anncwb** [comment]
使用nodejs 14以上

**Comment by lisonge** [comment]
@anncwb 
package.json should be added   `engines` constraint
